// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpz-38fPyjmua-WeEp7KQIqD4eEw6zEXw',
    appId: '1:833668235764:web:07fea1d042168bb252f9a1',
    messagingSenderId: '833668235764',
    projectId: 'marketplaceapp-edc72',
    authDomain: 'marketplaceapp-edc72.firebaseapp.com',
    storageBucket: 'marketplaceapp-edc72.firebasestorage.app',
    measurementId: 'G-JPH7WSLEWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkw5LGdVh5i4kMv-Bh3TBAAT1_GY_2U8',
    appId: '1:833668235764:android:ec8bfd23af2c0e0e52f9a1',
    messagingSenderId: '833668235764',
    projectId: 'marketplaceapp-edc72',
    storageBucket: 'marketplaceapp-edc72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABZet13Hy3BqE2O6mGGdO-SyCWhcSmRwk',
    appId: '1:833668235764:ios:1abbfe39bef331b452f9a1',
    messagingSenderId: '833668235764',
    projectId: 'marketplaceapp-edc72',
    storageBucket: 'marketplaceapp-edc72.firebasestorage.app',
    iosBundleId: 'com.example.energyMeasuresMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABZet13Hy3BqE2O6mGGdO-SyCWhcSmRwk',
    appId: '1:833668235764:ios:1abbfe39bef331b452f9a1',
    messagingSenderId: '833668235764',
    projectId: 'marketplaceapp-edc72',
    storageBucket: 'marketplaceapp-edc72.firebasestorage.app',
    iosBundleId: 'com.example.energyMeasuresMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpz-38fPyjmua-WeEp7KQIqD4eEw6zEXw',
    appId: '1:833668235764:web:b38ce847720090f152f9a1',
    messagingSenderId: '833668235764',
    projectId: 'marketplaceapp-edc72',
    authDomain: 'marketplaceapp-edc72.firebaseapp.com',
    storageBucket: 'marketplaceapp-edc72.firebasestorage.app',
    measurementId: 'G-FB29LZ81K7',
  );
}
